### ISSUE TITLE
signal SIGSEGV: segmentation violation caused by embedSendOptions

### ISSUE THREAD

**Issue by shuiRong** [tucnak/telebot#336]
INFO: the server is a VPS purchased recently.

`cat /proc/version`
> Linux version 5.4.0-26-generic (buildd@lcy01-amd64-029) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))

`head -n 1 /etc/issue`
> Ubuntu 20.04 LTS \n \l

`go version`
> go version go1.15.5 linux/amd64

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8b5446]

goroutine 1 [running]:
gopkg.in/tucnak/telebot%2ev2.(*Bot).embedSendOptions(0x0, 0xc00017e780, 0x0)
        /root/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.3.5/util.go:149 +0x26
gopkg.in/tucnak/telebot%2ev2.(*Bot).sendText(0x0, 0xa59ea0, 0xc0001c8000, 0xc00135f080, 0x40, 0x0, 0x10, 0x906860, 0xc001092301)
        /root/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.3.5/api.go:159 +0x12c
gopkg.in/tucnak/telebot%2ev2.(*Bot).Send(0x0, 0xa59ea0, 0xc0001c8000, 0x906a20, 0xc0013a4950, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.3.5/bot.go:524 +0xc7
main.main()
        /root/code/tg-channel-update-bot/main.go:70 +0x1a5
exit status 2
```

`main.go:70` is `bot.Send(chat, value.Title)`

**What I confused is that the code is running normally on my computer(Ubuntu 20.04 LTS).**

**Comment by demget** [comment]
Can you show a full related piece of code above the main.go:70?

**Comment by shuiRong** [comment]
@demget  the purpose of the method is to parse RSS and send it to a TG channel.

**main.go**
```
func main() {
	// 获取数据库中的期号
	numberInDB, _ := get("number")

	for i := len(feed.Items) - 1; i >= 0; i-- {
		value := feed.Items[i]
		currentNumber := parseTitle(value.Title)
		if currentNumber == 0 {
			continue
		}
		if currentNumber <= numberInDB {
			continue
		}

		dom := parseHTML(value.Content)

		time.Sleep(time.Second * time.Duration(interval))
                 // ______ main.go:70 is here. _____
		bot.Send(chat, value.Title)

		// 更新期号
		numberInDB = currentNumber
		set("number", currentNumber)

		var pics []string
		dom.Find(".md p").Each(func(_ int, s *goquery.Selection) {
			// 根据自节点的长度来判断当前p元素是标题，还是标题下的图片。
			// 0 是标题，1是图片
			childLength := s.Children().Length()
			if childLength == 0 {
				// 表示第n（n>1）个标题处，在这里可以把上一个item发出去了
				if len(pics) > 0 {
					album := make(tb.Album, 0, len(pics))
					for _, pic := range pics {
						album = append(album, &tb.Photo{File: tb.FromURL(pic)})
					}
					bot.SendAlbum(chat, album)
					// 重置数组
					pics = nil
				}
				time.Sleep(time.Second * time.Duration(interval))
				bot.Send(chat, s.Text())
			} else {
				pics = append(pics, s.Text())
			}
		})

		// 最后还有一组图片需要发出来
		if len(pics) > 0 {
			album := make(tb.Album, 0, len(pics))
			for _, pic := range pics {
				album = append(album, &tb.Photo{File: tb.FromURL(pic)})
			}
			time.Sleep(time.Second * time.Duration(interval))
			bot.SendAlbum(chat, album)
			// 重置数组
			pics = nil
		}
	}
}
```

**Comment by shuiRong** [comment]
weird but solved.

Seems It's my fault. I write`err.Error()`(in method `set()`) ant not judge If it's `nil` before. But still confusing why the trace stack tells the wrong line(main.go:70).
