### ISSUE TITLE
Dynamic handlers and concurrent handlers read and write

### ISSUE THREAD

**Issue by meskio** [tucnak/telebot#609]
We used to have a [piece of code like](https://gitlab.torproject.org/shelikhoo/rdsys/-/blob/dee9290a21d8bbb8d71042ae08d39643f149153d/pkg/presentation/distributors/telegram/telegram.go#L71):
```go
bot, _ := tb.NewBot(tb.Settings{
	Token:  token,
	Poller: &tb.LongPoller{Timeout: TelegramPollTimeout},
})

bot.Handle("/start", func(c tb.Context) error {
	var (
		menu       = &tb.ReplyMarkup{ResizeKeyboard: true}
		btnHelp    = menu.Text("Help")
	)

	menu.Reply(
		menu.Row(btnHelp),
	)
 
	t.bot.Handle(&btnHelp, func(c tb.Context) error {
		return c.Send("help", menu)
	})

	return bot.Send(c.Sender(), "Welcome!", menu)
})
```

But that will crash with a lot of concurrent users, as the handlers are stored in a map and adding a handler could produce a read and a write simultaneous:
```
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: fatal error: concurrent map read and map write
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: goroutine 1 [running]:
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: gopkg.in/telebot%2ev3.(*Bot).handle(...)
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]:         /home/user/go/pkg/mod/gopkg.in/telebot.v3@v3.1.2/update.go:285
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: gopkg.in/telebot%2ev3.(*Bot).ProcessUpdate(0xc0001b0ea0, {0x9bf696a, 0xc000264b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]:         /home/user/go/pkg/mod/gopkg.in/telebot.v3@v3.1.2/update.go:55 +0x288
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: gopkg.in/telebot%2ev3.(*Bot).Start(0xc0001b0ea0)
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]:         /home/user/go/pkg/mod/gopkg.in/telebot.v3@v3.1.2/bot.go:219 +0x1cc
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: gitlab.torproject.org/tpo/anti-censorship/rdsys/pkg/presentation/distributors/telegram.(*TBot).Start(...)
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]:         /home/user/dev/rdsys/pkg/presentation/distributors/telegram/telegram.go:90
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: gitlab.torproject.org/tpo/anti-censorship/rdsys/pkg/presentation/distributors/telegram.InitFrontend(0xc0001a6000)
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]:         /home/user/dev/rdsys/pkg/presentation/distributors/telegram/telegram.go:68 +0x433
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]: main.main()
Feb 04 18:14:51 polyanthum rdsys-distributors[967517]:         /home/user/dev/rdsys/cmd/distributors/main.go:58 +0x4c3
```

We fixed this by initializing the button handlers [only once for all conversations](https://gitlab.torproject.org/shelikhoo/rdsys/-/commit/c949888812a8879ef25d68751d3db55c8e4e198c):
```go
var (
	menu       = &tb.ReplyMarkup{ResizeKeyboard: true}
	btnHelp    = menu.Text("Help")
)

menu.Reply(
	menu.Row(btnHelp),
)

bot, _ := tb.NewBot(tb.Settings{
	Token:  token,
	Poller: &tb.LongPoller{Timeout: TelegramPollTimeout},
})

bot.Handle("/start", func(c tb.Context) error {
	return bot.Send(c.Sender(), "Welcome!", menu)
})


t.bot.Handle(&btnHelp, func(c tb.Context) error {
	return c.Send("help", menu)
})
```

Now we are working on adding i18n and will want to be able to set the button text dynamically depending on the locale of the user. What is the recommended way to do this? I could create one button per language and select the right ones in the */start* handler, but sounds a bit convoluted.

Does it make sense to add a `sync.RWMutex` to the handlers map in telebot?

**Comment by demget** [comment]
You can't use `Handle` inside another `Handle` function.

For the i18n support see `telebot/layout` package.
Usage example: https://github.com/handybots/azartio

**Comment by meskio** [comment]
If I understand correctly the layout package requires to have the translations in yaml file with the telebot format. I'm looking for a way to provide translations programmatically, as we use go-i18n in the program and will require some hacks around to produce those yaml files.

I'm solving the problem by producing a set of buttons per locale on the initialization and handing the right ones on each reply.

Thank you for the fast answer.
