### ISSUE TITLE
Can't use localizer with layout

### ISSUE THREAD

**Issue by qwaykee** [tucnak/telebot#635]
Hello,
Whenever I try to use lt.Text(c, "some-text"), I get this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9558ab]

goroutine 12 [running]:
gopkg.in/telebot.v3/layout.(*Layout).SetLocale(0x0, {0xcae330, 0xc0004a6000}, {0xbab78f, 0x2})
	/home/qwaykee/go/pkg/mod/gopkg.in/telebot.v3@v3.2.1/layout/layout.go:165 +0x2b
main.main.(*Layout).Middleware.func2.1({0xcae330, 0xc0004a6000})
	/home/qwaykee/go/pkg/mod/gopkg.in/telebot.v3@v3.2.1/layout/middleware.go:34 +0xd4
gopkg.in/telebot%2ev3.(*Bot).Handle.func1({0xcae330, 0xc0004a6000})
	/home/qwaykee/go/pkg/mod/gopkg.in/telebot.v3@v3.2.1/bot.go:180 +0x4b
gopkg.in/telebot%2ev3.(*Bot).runHandler.func1()
	/home/qwaykee/go/pkg/mod/gopkg.in/telebot.v3@v3.2.1/update.go:357 +0x35
created by gopkg.in/telebot%2ev3.(*Bot).runHandler in goroutine 1
	/home/qwaykee/go/pkg/mod/gopkg.in/telebot.v3@v3.2.1/update.go:364 +0xb5
exit status 2
```

Here is my code:
```golang
package main

import (
	"gopkg.in/telebot.v3"
	"gopkg.in/telebot.v3/layout"
	"log"
)

var (
	lt 	*layout.Layout
	b 	*telebot.Bot
)

func init() {
	log.Println("initialization")

	// load layout
	lt, err := layout.New("config.yml")
	if err != nil {
		log.Fatalf("layout: %v", err)
	}

	// create bot
	b, err = telebot.NewBot(lt.Settings())
	if err != nil {
		log.Fatalf("telebot: %v", err)
	}
}

func main() {
	// doesn't work neither
	// b.Use(lt.Middleware("en", func(r telebot.Recipient) string {
	// 	return "en"
	// }))

	b.Use(lt.Middleware("en"))

	b.Handle("/start", func(c telebot.Context) error {
		return c.Send(lt.Text(c, "start"))
	})

	log.Println("start")
	b.Start()
}
```

Here is my config.yml file:
```yaml
settings:
  token: ...
  locales_dir: locales
  parse_mode: markdown
```

And my en.yml file which is located in locales/
```yaml
start: hello
```

My file structure looks like this:
- main.go
- config.yml
- locales/
- - en.yml
- - fr.yml

I also tried TextLocale("en", "start") and I get the same error.
Am I doing something wrong?
All other functions of the layout package works just fine except everything related to localizing.

**Comment by demget** [comment]
`lt, err := layout.New("config.yml")` is wrong, you are shadowing the global `lt` variable. Move the initialization from the `init()` to the `main()`. Avoid using `init()` function until you know how and when you should really have it.

**Comment by qwaykee** [comment]
It works, thank you very much
