### ISSUE TITLE
Panic on bot.Stop() v4.0.0-beta.4

### ISSUE THREAD

**Issue by ofstudio** [tucnak/telebot#760]
```
panic: close of closed channel
goroutine 44 [running]:
gopkg.in/telebot%2ev4.(*Webhook).waitForStop(...)
	gopkg.in/telebot.v4@v4.0.0-beta.4/webhook.go:161
gopkg.in/telebot%2ev4.(*Webhook).Poll.func1(0xc000450a10)
	gopkg.in/telebot.v4@v4.0.0-beta.4/webhook.go:148 +0x2f
created by gopkg.in/telebot%2ev4.(*Webhook).Poll in goroutine 40
	gopkg.in/telebot.v4@v4.0.0-beta.4/webhook.go:147 +0x18a
```

the code
```go
go bot.Start() // 1. Start the bot
<-ctx.Done()   // 2. Wait for context cancel on SIGING or SIGTERM
bot.Stop()     // 3. Stop the bot
// ^^^^ Panic goes here!

**Comment by evgeniy-krivenko** [comment]
The same error with v3.3.8

```
 panic: close of closed channel

 goroutine 80 [running]:
 gopkg.in/telebot%2ev3.(*Webhook).waitForStop(...)
  /go/pkg/mod/gopkg.in/telebot.v3@v3.3.8/webhook.go:155
gopkg.in/telebot%2ev3.(*Webhook).Poll.func1(0xc00007ff80)
  /go/pkg/mod/gopkg.in/telebot.v3@v3.3.8/webhook.go:142 +0x2f
created by gopkg.in/telebot%2ev3.(*Webhook).Poll in goroutine 59
  /go/pkg/mod/gopkg.in/telebot.v3@v3.3.8/webhook.go:141 +0x187
```

**Comment by molizz** [comment]
1. Use webhook & webhook.ServeHTTP(c.Writer, c.Request) in Gin (http)
2. bot.Start()
3. sleep(1s)
4. bot.Stop() -> panic!!

<img width="604" alt="Image" src="https://github.com/user-attachments/assets/05e982d0-57c0-49f2-af71-6db4047246f9" />

<img width="811" alt="Image" src="https://github.com/user-attachments/assets/eae424e1-d349-477c-bcc8-986fc6b320ff" />
